export const PASSWORD_COMPLEXITY = /(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]+/;
export const PHONE_FORMAT = /^\d+$/;
export const MIN_PASSWORD_LENGTH = 6;
export const MIN_FIRST_NAME_LEN = 4;
export const MAX_FIRST_NAME_LEN = 32;
export const MIN_LAST_NAME_LEN = 4;
export const MAX_LAST_NAME_LEN = 32;
export const MIN_TITLE_LEN = 16;
export const MAX_TITLE_LEN= 64;
export const MIN_CONTENT_LEN = 32;
export const MAX_CONTENT_LEN = 8192;
export const MIN_TAG_LEN = 3;
export const MAX_TAG_LEN = 10;
export const MIN_TAG_NUM = 1;
export const MAX_TAG_NUM = 6;